version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tolo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=G7e3KSMED
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "cd src
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/tolo
    ports:
      - "1996:8000"
    environment:
      - PROD=1
      - POSTGRES_NAME=tolo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=G7e3KSMED
    depends_on:
      - db